// OpenQASM 2.0 - ZZ Feature Map for QSVM
// Generated by quantum-simulation-qsvm (Rust)

OPENQASM 2.0;
include "qelib1.inc";

// 4 qubits for 4 features
qreg q[4];
creg c[4];

// Layer 1: Hadamard gates - create superposition |+⟩
h q[0];
h q[1];
h q[2];
h q[3];

// Layer 2: RZ rotations - encode features into phases
rz(-1.270177) q[0];
rz(-0.297864) q[1];
rz(0.055018) q[2];
rz(0.019720) q[3];

// Layer 3: CNOT entanglement - create feature correlations
cx q[0],q[1];
cx q[1],q[2];
cx q[2],q[3];

// Layer 4: Second RZ rotation - deeper encoding
rz(-2.540355) q[0];
rz(-0.595728) q[1];
rz(0.110036) q[2];
rz(0.039441) q[3];

// Uncomment below to add measurements:
// measure q[0] -> c[0];
// measure q[1] -> c[1];
// measure q[2] -> c[2];
// measure q[3] -> c[3];
