#!/usr/bin/env python3
"""
Qiskit loader for QSVM Feature Map
Generated by quantum-simulation-qsvm (Rust)

Usage:
    1. Install qiskit: pip install qiskit qiskit-aer
    2. Run this script: python load_qasm.py
"""

from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator

# Load the QASM file generated by Rust
circuit = QuantumCircuit.from_qasm_file("feature_map.qasm")

# Print circuit info
print(f"Circuit has {circuit.num_qubits} qubits")
print("\nCircuit diagram:")
print(circuit.draw())

# Simulate the circuit
simulator = AerSimulator()
circuit.save_statevector()
job = simulator.run(circuit)
result = job.result()
statevector = result.get_statevector()

print(f"\nStatevector (first 8 amplitudes):")
for i, amp in enumerate(statevector[:8]):
    print(f"  |{i:04b}⟩: {amp:.4f}")

# To run on real IBM hardware:
# from qiskit_ibm_runtime import QiskitRuntimeService
# service = QiskitRuntimeService()
# backend = service.backend("ibm_brisbane")
# job = backend.run(circuit)
